### ISSUE TITLE
Extract meta information from post

### ISSUE THREAD

**Issue by daklassen** [adessoAG/jekyll2cms#4]
**Task:** Create a controller that provides necessary method for extracting meta information from blog post.

**Given:** A markdown file with following header:
```
---
id: 42
layout: article
title: Github's Fork & Pull Workflow for Git Beginners
categories: [hacks]
modified: 2017-01-02
author: tom
tags: [git, github, pull request, branch, fork, howto, guide, pull]
comments: true
ads: false
image:
  feature: 
  teaser: teaser/github-mark.png
  thumb:
---
```

**Wanted**: A controller class that extracts information from markdown file and stores it into a **hashmap**.
